### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aiyzou** [codewithriza/SlotBot#1]
![IMG_8599](https://github.com/codewithriza/SlotBot/assets/164605326/a1799928-6c44-4093-91c4-3a13a827e88f)

**Comment by codewithriza** [comment]
It seems there's an issue with the JSON file. Please make sure you have filled in the token and staff role ID, as well as any other necessary role IDs, properly. Additionally, there might be more role IDs to be pasted in the `main.py` file; make sure you have walked through it. I have already mentioned it as a comment. Don't forget to go to the last line of `main.py` to set the token :)

**Comment by codewithriza** [comment]
Fixed the issue
